# Generated by Django 5.0.7 on 2025-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_task_message_documentversion_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
